import type { Task, User, Group, ChatMessage } from "@/types";

export const mockCurrentUser: User = {
  id: 1,
  name: "Kai",
  email: "kai@example.com",
  role: "React & Node.js 工程师",
  initials: "K",
  color: "from-orange-400 to-orange-500",
};

export const mockUsers: User[] = [
  mockCurrentUser,
  {
    id: 2,
    name: "Mom",
    email: "mom@example.com",
    initials: "M",
    color: "from-pink-400 to-pink-500",
  },
  {
    id: 3,
    name: "Dad",
    email: "dad@example.com",
    initials: "D",
    color: "from-blue-400 to-blue-500",
  },
  {
    id: 4,
    name: "Sister",
    email: "sister@example.com",
    initials: "S",
    color: "from-purple-400 to-purple-500",
  },
  // 登山俱乐部成员
  {
    id: 5,
    name: "张峰",
    email: "zhangfeng@example.com",
    initials: "ZF",
    color: "from-green-400 to-green-500",
  },
  {
    id: 6,
    name: "李雪",
    email: "lixue@example.com",
    initials: "LX",
    color: "from-cyan-400 to-cyan-500",
  },
  {
    id: 7,
    name: "王强",
    email: "wangqiang@example.com",
    initials: "WQ",
    color: "from-teal-400 to-teal-500",
  },
  {
    id: 8,
    name: "陈晨",
    email: "chenchen@example.com",
    initials: "CC",
    color: "from-amber-400 to-amber-500",
  },
  {
    id: 9,
    name: "赵敏",
    email: "zhaomin@example.com",
    initials: "ZM",
    color: "from-rose-400 to-rose-500",
  },
  // 美食分享成员
  {
    id: 10,
    name: "刘美食",
    email: "liumeishi@example.com",
    initials: "LM",
    color: "from-yellow-400 to-yellow-500",
  },
  {
    id: 11,
    name: "周大厨",
    email: "zhoudachu@example.com",
    initials: "ZD",
    color: "from-red-400 to-red-500",
  },
  {
    id: 12,
    name: "吴吃货",
    email: "wuchihuo@example.com",
    initials: "WC",
    color: "from-indigo-400 to-indigo-500",
  },
  {
    id: 13,
    name: "郑甜品",
    email: "zhengtianpin@example.com",
    initials: "ZT",
    color: "from-fuchsia-400 to-fuchsia-500",
  },
  // 周末骑行成员
  {
    id: 14,
    name: "孙骑士",
    email: "sunqishi@example.com",
    initials: "SQ",
    color: "from-lime-400 to-lime-500",
  },
  {
    id: 15,
    name: "马速度",
    email: "masudu@example.com",
    initials: "MS",
    color: "from-emerald-400 to-emerald-500",
  },
  {
    id: 16,
    name: "杨飞轮",
    email: "yangfeilun@example.com",
    initials: "YF",
    color: "from-sky-400 to-sky-500",
  },
  {
    id: 17,
    name: "徐风行",
    email: "xufengxing@example.com",
    initials: "XF",
    color: "from-violet-400 to-violet-500",
  },
  {
    id: 18,
    name: "林畅行",
    email: "linchangxing@example.com",
    initials: "LC",
    color: "from-orange-400 to-orange-500",
  },
  {
    id: 19,
    name: "胡极速",
    email: "hujisu@example.com",
    initials: "HJ",
    color: "from-pink-400 to-pink-500",
  },
  {
    id: 20,
    name: "谢单车",
    email: "xiedanche@example.com",
    initials: "XD",
    color: "from-slate-400 to-slate-500",
  },
];

export const mockGroups: Group[] = [
  {
    id: 1,
    name: "温馨小家",
    icon: "🏠",
    role: "owner",
    memberCount: 3,
    inviteCode: "8859",
  },
  {
    id: 2,
    name: "登山俱乐部",
    icon: "⛰️",
    role: "member",
    memberCount: 6,
    inviteCode: "6677",
  },
  {
    id: 3,
    name: "美食分享",
    icon: "🍜",
    role: "owner",
    memberCount: 5,
    inviteCode: "3344",
  },
  {
    id: 4,
    name: "周末骑行",
    icon: "🚴",
    role: "owner",
    memberCount: 8,
    inviteCode: "9921",
  },
];

// 群组成员映射表：groupId -> userIds（第一个成员为群主）
export const mockGroupMembers: Record<number, number[]> = {
  1: [1, 2, 3], // 温馨小家：Kai(群主), Mom, Dad
  2: [5, 1, 6, 7, 8, 9], // 登山俱乐部：张峰(群主) + Kai和其他登山爱好者
  3: [1, 10, 11, 12, 13], // 美食分享：Kai(群主) + 4个美食爱好者
  4: [1, 14, 15, 16, 17, 18, 19, 20], // 周末骑行：Kai(群主) + 7个骑行爱好者
};

export const mockTasks: Task[] = [
  // 添加本周其他日期的任务
  {
    id: 6,
    title: "团队周会",
    description: "讨论本周进度和下周计划",
    status: "pending",
    priority: "medium",
    dueDate: "2026-02-02", // 周一
    startTime: "10:00",
    endTime: "11:00",
    isAllDay: false,
    groupId: undefined,
    createdBy: 1,
    assignedTo: [1],
    source: "human",
    isRecurring: true,
    recurringRule: {
      freq: "weekly",
      interval: 1,
      startDate: "2026-02-02",
      daysOfWeek: [1], // 每周一
    },
    createdAt: "2026-01-29T10:00:00Z",
    updatedAt: "2026-01-29T10:00:00Z",
  },
  {
    id: 7,
    title: "健身房锻炼",
    description: "胸部+三头肌训练",
    status: "pending",
    priority: "low",
    dueDate: "2026-02-03", // 周二
    startTime: "18:00",
    endTime: "19:30",
    isAllDay: false,
    groupId: undefined,
    createdBy: 1,
    assignedTo: [1],
    source: "human",
    isRecurring: true,
    recurringRule: {
      freq: "weekly",
      interval: 1,
      startDate: "2026-02-03",
      daysOfWeek: [2, 4, 6], // 周二、周四、周六
    },
    createdAt: "2026-01-29T10:00:00Z",
    updatedAt: "2026-01-29T10:00:00Z",
  },
  {
    id: 8,
    title: "准备月度报告",
    description: "整理1月份的工作总结",
    status: "pending",
    priority: "high",
    dueDate: "2026-02-04", // 周三
    startTime: "14:00",
    endTime: "17:00",
    isAllDay: false,
    groupId: undefined,
    createdBy: 1,
    assignedTo: [1],
    source: "human",
    isRecurring: false,
    createdAt: "2026-01-29T10:00:00Z",
    updatedAt: "2026-01-29T10:00:00Z",
  },
  {
    id: 9,
    title: "家庭聚餐",
    description: "外婆生日庆祝",
    status: "pending",
    priority: "high",
    dueDate: "2026-02-05", // 周四
    startTime: "18:00",
    isAllDay: false,
    groupId: 1,
    createdBy: 2,
    assignedTo: [1, 2, 3, 4],
    source: "human",
    isRecurring: false,
    createdAt: "2026-01-29T10:00:00Z",
    updatedAt: "2026-01-29T10:00:00Z",
  },
  {
    id: 10,
    title: "周末大扫除",
    description: "清洁厨房和卫生间",
    status: "pending",
    priority: "medium",
    dueDate: "2026-02-07", // 周六
    isAllDay: true,
    groupId: 1,
    createdBy: 1,
    assignedTo: [1, 2],
    source: "human",
    isRecurring: false,
    createdAt: "2026-01-29T10:00:00Z",
    updatedAt: "2026-01-29T10:00:00Z",
  },
  {
    id: 1,
    title: "复习React Hooks",
    description: "整理useCallback和useMemo的使用场景",
    status: "pending",
    priority: "medium",
    dueDate: "2026-01-30",
    startTime: "14:00",
    endTime: "15:30",
    isAllDay: false,
    groupId: undefined,
    createdBy: 1,
    assignedTo: [1],
    source: "human",
    isRecurring: false,
    createdAt: "2026-01-29T10:00:00Z",
    updatedAt: "2026-01-29T10:00:00Z",
  },
  {
    id: 2,
    title: "晚间瑜伽",
    description: "30分钟放松运动",
    status: "pending",
    priority: "low",
    dueDate: "2026-01-30",
    isAllDay: true,
    groupId: undefined,
    createdBy: 1,
    assignedTo: [1],
    source: "human",
    isRecurring: true,
    recurringRule: {
      freq: "weekly",
      interval: 1,
      startDate: "2026-01-27",
      endDate: "2026-06-30",
      daysOfWeek: [1, 3, 5],
    },
    createdAt: "2026-01-27T10:00:00Z",
    updatedAt: "2026-01-27T10:00:00Z",
  },
  {
    id: 3,
    title: "给客厅植物浇水",
    description: "记得龟背竹需要喷雾保湿",
    status: "pending",
    priority: "medium",
    dueDate: "2026-01-30",
    startTime: "09:00",
    endTime: "09:15",
    isAllDay: false,
    groupId: 1,
    createdBy: 2,
    assignedTo: [1],
    source: "ai",
    isRecurring: false,
    createdAt: "2026-01-29T08:00:00Z",
    updatedAt: "2026-01-29T08:00:00Z",
  },
  {
    id: 4,
    title: "取干洗衣物",
    description: "取衣单在冰箱磁贴上",
    status: "pending",
    priority: "high",
    dueDate: "2026-01-30",
    startTime: "17:30",
    isAllDay: false,
    groupId: 1,
    createdBy: 1,
    assignedTo: [1, 2],
    source: "human",
    isRecurring: false,
    createdAt: "2026-01-29T09:00:00Z",
    updatedAt: "2026-01-29T09:00:00Z",
  },
  {
    id: 5,
    title: "采购日用品",
    description: "牛奶、面包、水果",
    status: "completed",
    priority: "low",
    dueDate: "2026-01-30",
    isAllDay: true,
    groupId: 1,
    createdBy: 1,
    assignedTo: [2],
    completedBy: 2,
    completedAt: "2026-01-30T11:30:00Z",
    source: "human",
    isRecurring: false,
    createdAt: "2026-01-29T07:00:00Z",
    updatedAt: "2026-01-30T11:30:00Z",
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: 1,
    role: "ai",
    content: "你好！告诉我你的任务需求，我来帮你创建。",
    timestamp: "2026-01-30T10:00:00Z",
  },
];
